### ISSUE TITLE
Please add support for the ‘hh:mm:ss.zzzzzSfffff’ time format with fractional sub-seconds as described in § 5.11

### ISSUE THREAD

**Issue by TomArrow** [ebu/libadm#118]
I see the specification appears to allow for a fractional representation of sub-seconds, which allows to specify the sub-seconds in audio samples. This would be pretty useful and circumvent the necessity to do a conversion from sample times to nanoseconds, which I think has the potential to introduce rounding errors, which then in turn needs to be accounted for because the specification demands that audioBlockFormat elements be contiguous and that there be no overlap or gaps in between them.

Ideally the time could simply be specified in audio samples throughout the file.

**Comment by tomjnixon** [comment]
The referenced PR was merged.
