### ISSUE TITLE
adm/export.h missing from include folder 

### ISSUE THREAD

**Issue by 17jmcl** [ebu/libadm#156]
adm/export.h used in various program header files (example in errors.hpp) not found in source code.

**Comment by tomjnixon** [comment]
Hi, sorry for the delay.

That file is generated by cmake here:

https://github.com/ebu/libadm/blob/56e7bc512823eb83b8ad48c24cbd3c41e817f4b0/src/CMakeLists.txt#L114-L129

Are you using cmake to build this? if so, it may be a bug. If not, there are some instructions in the README for that.

**Comment by 17jmcl** [comment]
Hi, no problem. No I am not, I'll try using cmake now. Thank you!
