### ISSUE TITLE
Option to write common definitions

### ISSUE THREAD

**Issue by sounddroid** [ebu/libadm#52]
```
As the idea of the common definitions is, that those ADM elements don’t need to be written, even though we added common definition ADM elements to our document the XML writer does not write them.
```

Hello. I understand that this library does not write out the common definitions if they are being used in an `admDoc`, but is there an option to override this?

**Comment by benjamin-weiss** [comment]
It is trivial to add an option to the writer, which does that, but I don't think it is a good idea to do so.

Why do you need this feature?

**Comment by sounddroid** [comment]
Hey @benjamin-weiss ! Thanks for the quick reply. For a DAW, like Pro Tools, it is looking for a complete <axml> block without referring to common_definitions.xml. They need the ADM to be fully self-describing without external links in order to import the audio with metadata (via Import Session Data). With a fully self-describing ADM, Pro Tools can automatically group audioObjects and so on.

**Comment by benjamin-weiss** [comment]
Sorry, but I still don't think it is a good idea. If ProTools needs an ADM which does not use the common definitions, just give it to it and don't try to write the common definitions. It is easy to write a little helper function to make your life easier when you create your ADM. (beware: completely untested code following)

```cpp
struct SimpleDirectSpekaersHolder {
  std::shared_ptr<AudioObject> audioObject;
  std::vector<std::shared_ptr<AudioTrackUid>> audioTrackUids;
};

struct SimpleSpeaker {
  std::string name;
  float azimuth;
  float elevation;
}

SimpleDirectSpeakersHolder
createDirectSpeakers(std::string name, std::vector<SimpleSpeaker> speakers) {
  SimpleDirectSpeakersHolder holder;
  holder.audioObject = AudioObject::create();
  auto audioPackFormat = AudioPackFormat::create(
      AudioPackFormatName(name), TypeDefinition::DIRECT_SPEAKERS);
  for (auto speaker : speakers) {
    auto audioStreamFormat = AudioStreamFormat::create(
        AudioStreamFormatName(name), FormatDefinition::PCM);
    auto audioTrackFormat = AudioTrackFormat::create(AudioTrackFormatName(name),
                                                     FormatDefinition::PCM);
    auto audioChannelFormat = AudioChannelFormat::create(
        AudioChannelFormatName(name), TypeDefinition::OBJECTS);
    auto audioTrackUid = AudioTrackUid::create();

    // reference
    holder.audioObject->addReference(audioPackFormat);
    audioPackFormat->addReference(audioChannelFormat);
    audioStreamFormat->setReference(audioChannelFormat);
    audioTrackFormat->setReference(audioStreamFormat);
    audioObject->addReference(audioTrackUid);
    audioTrackUid->setReference(audioTrackFormat);
    audioTrackUid->setReference(audioPackFormat);
    holder.audioTrackUids.push_back(audioTrackUid);
  }
  return holder;
}
```

**Comment by sounddroid** [comment]
Thanks for the example code @benjamin-weiss .
