### ISSUE TITLE
Gain Sub-Element Not Included in All AudioBlockFormats

### ISSUE THREAD

**Issue by walleym** [ebu/libadm#66]
In the standard. The gain sub-element of AudioBlockFormat is listed as common to all implementations of AudioBlockFormat. As far as I can see here, it is only implemented in the AudioBlockFormatObjects class.

**Comment by tomjnixon** [comment]
Hi,

So far this library only implements features from BS.2076-1, which only includes a gain parameter in the Objects type. We're planning on updating this soon.
