### ISSUE TITLE
Support fractional time format

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/libadm#69]
In [2076-2](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf). time format now includes this fractional based format: hh:mm:ss.xxxxxSyyyyy (where xxxxx & yyyyy the numerator and denominator of a fraction, e.g. 12000S48000).

### From the standard

>5.11 Time parameters format
>
>Time-related parameters shall have the format of ‘hh:mm:ss.zzzzz’ or ‘hh:mm:ss.zzzzzSfffff’.
>
>‘hh:mm:ss.zzzzz’ indicates hours, minutes, seconds. The number of decimal places for the seconds should be a minimum of 5. There should be enough decimal places used for sample-accurate timing. For example, 01:34:16.25000.
>
>‘hh:mm:ss.zzzzzSfffff’ indicates hours, minutes, seconds with a fractional representation  of  sub-seconds.  The  zzzzz  digits  represent  the  numerator  of  a  fraction,  and  the  fffff  digits  represent  the denominator. The number of digits for zzzzz and fffff should be at least five each. This format allows a sample-based representation oftime to be used, where zzzzz is the number of samples, and fffff is the sample-rate. The value of zzzzz should be less than fffff to ensure a fraction less than one. Both values   should   not   be   negative,   and   fffff   should   be   greater   than   zero. For example, 01:34:16.12000S48000 is the same as 01:34:16.25000.

### Definition of done
For all time based parameters in libadm we are able to:
- [ ] correctly parse a fractional format time parameter from XML, then write it back again without modification. Given a valid timestamp, the same timestamp should be written in the same format.
- [ ] create both ns and fractional time parameters using the libadm API
- [ ] modify an existing time based parameter, changing representation if required
- [ ] correctly write newly created or modified time based parameters to XML in the chosen format
- [ ] continue to parse and write ns timestamps correctly
- [ ] provide useful feedback when invalid timestamps of either representation are encountered

**Comment by rsjtaylor** [comment]
### Things to discuss

* How to store: Currently use std::chrono::ns, in the fractional case do we want to preserve the representation for (at least) the common sample rates to avoid rounding errors? Maybe look at [flicks](https://github.com/facebookarchive/Flicks)
* Interface: Should we specify ratio when creating elements or globally on import/export, or some combination?
* Should we allow lossy ratio conversions at all and if we do should we inform/warn, and how?

### Relevant areas of source:
[time.hpp](https://github.com/ebu/libadm/blob/master/include/adm/elements/time.hpp)
[time.cpp](https://github.com/ebu/libadm/blob/master/src/elements/time.cpp)
[xml_parser.hpp](https://github.com/ebu/libadm/blob/master/include/adm/private/xml_parser.hpp)
[xml_parser.cpp](https://github.com/ebu/libadm/blob/master/src/private/xml_parser.cpp)
[xml_writer.hpp](https://github.com/ebu/libadm/blob/master/include/adm/private/xml_writer.hpp)
[xml_writer.cpp](https://github.com/ebu/libadm/blob/master/src/private/xml_writer.cpp)
[audio_block_format_objects.hpp](https://github.com/ebu/libadm/blob/master/include/adm/elements/audio_block_format_objects.hpp)
[audio_block_format_objects.cpp](https://github.com/ebu/libadm/blob/master/src/elements/audio_block_format_objects.cpp)

And other block formats, other places where times are used.

**Comment by tomjnixon** [comment]
The Plan:
- define representation struct/variant
- implement/test parsing and formatting
  - do this as new functions so that the rest of the library doesn't break
- replace nanoseconds with new time type
  - think about how to preserve backwards compatibility: ignore it; provide separate tags for time and fractional time; make new type convertible to ns

question: what level of testing do we need to do if we've already tested the parse/format functions

**Comment by rsjtaylor** [comment]
If the types you add don't have any non-trivial behaviour (i.e. they're just wrapped values) I'd say the parse/format should be enough, as there's implicit in that the ability to construct them / pass them to the parent element etc, and making those things explicit tests probably just makes the test suite more brittle without adding much.
I'd try and have a few edge cases & error cases in those parsing tests though.
