### ISSUE TITLE
Add gain sub-element and importance attribute to non object type audioBlockFormats

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/libadm#71]
In [2076-2](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf) gain sub-element and importance attribute are now available in all typeDefinitions of audioBlockFormat.

See section [12](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf#%5B%7B%22num%22%3A141%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C54%2C440%2C0%5D) for interpretation of these sub-elements.

### Things to discuss

* Is gain represented the same way everywhere (not necessarily interpreted the same way?), i.e. is one type enough?

**Comment by rsjtaylor** [comment]
maybe do #72 at the same time

**Comment by kristianhentschelbbc** [comment]
It would be good to do this after #104 is merged as that adds the new automatic base class to all block formats.
