### ISSUE TITLE
Add gainUnit attribute to gain subelements

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/libadm#74]
[2076-2](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf) adds an optional gainUnit attribute to the gain subelement of audioObject and audioBlockFormat
We should support this

>An  optional  gainUnit  attribute  (either ‘linear’ or ‘dB’) can be used to define the unit of the gain value. The default unit is ‘linear’.

**Comment by tomjnixon** [comment]
Should this be exposed to the user, or is it sufficient to convert dB gains to linear in the parser?

If it's exposed, would it make sense to have `get<Gain>()` convert dB to linear, and `get<GainDb>()` convert linear to dB?

**Comment by tomjnixon** [comment]
Random thoughts:

- If we store gains as linear internally, then dB gain values are more likely to suffer rounding issues when a file is passed through libadm, and it might not be possible to produce XML with nice round values. This can also make testing painful.

- The parser should probably be able to handle `-inf` and `-INF`, as both are mentioned in 2076-2. Exposing floating point values of -inf to the user seems a bit rude, but `pow(10, -inf)` does return 0 so maybe it's ok...

From these I'd probably store linear and dB separately (as a variant, so there's no storage overhead) and convert between them when either is requested.
