### ISSUE TITLE
allow multiple loudnessMetadata elements in audioProgramme and audioContent

### ISSUE THREAD

**Issue by tomjnixon** [ebu/libadm#84]
In BS.2076-2, there may be multiple `loudnessMetadata` elements in `audioProgramme` and `audioContent`; see tables 32 and 38,

**Comment by tomjnixon** [comment]
We're not sure what the API of this should be.

One option would be to wrap this in a class:

```cpp
struct LoudnessMetadatas {
  using tag = ...;
  std::vector<LoudnessMetadata> data;
};

audioObject.get<LoudnessMetadatas>().get();
audioObject.set(LoudnessMetadatas{std::vector<LoudnessMetadata>{...}});
```
... or to just use a `std::vector<LoudnessMetadata>` directly:

```cpp
using LoudnessMetadatas = std::vector<LoudnessMetadata>;
audioObject.get<LoudnessMetadatas>();
audioObject.set(std::vector<LoudnessMetadata>{...});
```

... or to add an API to `AudioObject` to add and remove `LoudnessMetadata`s:

```cpp
std::shared_ptr<LoudnessMetadata> loudnessMetadata = LoudnessMetadata::create();
audioObject.add(loudnessMetadata);
audioObject.remove(loudnessMetadata);
audioObject.getLoudnessMetadata() -> std::vector<std::shared_ptr<LoudnessMetadata>>
```

I think we both prefer option 2.

**Comment by tomjnixon** [comment]
The decision here should probably apply to #90, too

**Comment by rsjtaylor** [comment]
Elsewhere in the library where there is this sort of relationship (for example SpekerLabels in AudioBlockFormatDirectSpeakers) the plural type is just an alias for std::vector, then there are add() and remove() methods for the singular type in the parent.
