### ISSUE TITLE
Check code formatting (clang-format) in CI

### ISSUE THREAD

**Issue by kristianhentschelbbc** [ebu/libadm#85]
In #76 we found some instances of formatting not matching the expected clang-format and ended up polluting the diff (with format-on-save).

Perhaps we should run `clang-format -Werror -n src/**/*.[ch]pp include/**/*.[ch]pp tests/**/*.[ch]pp` (not sure if these glob patterns are exhaustive) as a check during continuous integration, to reject PR's that are not fully formatted.

**Comment by tomjnixon** [comment]
this was fixed a while ago
