### ISSUE TITLE
Add support for headLocked sub-element on audioObject and all flavours of audioBlockFormat

### ISSUE THREAD

**Issue by rsjtaylor** [ebu/libadm#91]
[2076-2](https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.2076-2-201910-I!!PDF-E.pdf) adds a new headLocked sub-element. This sub-element is optionally present on audioObject and audioBlockFormats of all types.

The meaning and default are the same in all places.

It is a flag (1 or 0).

> Indicates if the perceived location of the audio element is locked to the head (flag = 1) or not locked (flag = 0)
Default Value is 0

> The headLocked flag indicates that an audio object should lock to the listener’s head when the head is moved (yaw/pitch/roll). Therefore, a headphone renderer which uses head tracking should not track the object if headLocked is set to “1”. Figure 6 depicts  the  concept  of  enabled  and disabled  head-locked audio elements.The  default  state  (when  headLocked  is  not  present)  is  for  head-locking  to  be  off,  so  the  scene  of objects remains fixed relative to the moving head (the middle diagram in Fig.6). If headLocked is  present  in  the  audioOject  and  the  audioBlockFormat,  the  value  defined  in  the audioBlockFormat shall take precedence over the audioObject value. 

See cartesian flag on audioBlockFormat Objects for an example of something similar

**Comment by tomjnixon** [comment]
Now that there are common elements in all block types (this, #92 , #71 ), would it make sense to implement these in a super-class?

**Comment by tomjnixon** [comment]
Here's my attempt at automatically generating base classes with templates: https://github.com/ebu/libadm/compare/feature_gainunit...feature_automatic_base

It seems to work decently, and isn't too many LOC (breaking even when replacing 4 parameters with it).

I think the main downside would be more complicated error messages, but with GCC it's not that bad. e.g. when calling `has` with a tag that doesn't exist you get something like this normally:

```
../include/adm/elements/audio_block_format_objects.hpp:214:21: note: candidate: ‘bool adm::AudioBlockFormatObjects::has(adm::detail::ParameterTraits<adm::JumpPosition>::tag) const’
  214 |     ADM_EXPORT bool has(detail::ParameterTraits<JumpPosition>::tag) const;
      |                     ^~~
../include/adm/elements/audio_block_format_objects.hpp:214:25: note:   no known conversion for argument 1 from ‘Tag’ {aka ‘adm::AudioBlockFormatObjectsTag’} to ‘adm::detail::ParameterTraits<adm::JumpPosition>::tag’ {aka ‘adm::JumpPositionTag’}
  214 |     ADM_EXPORT bool has(detail::ParameterTraits<JumpPosition>::tag) const;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
or this with the automatic base:
```
../include/adm/detail/magic_base.hpp:62:23: note: candidate: ‘bool adm::detail::OptionalBase<T>::has(typename adm::detail::ParameterTraits<Parameter>::tag) const [with T = adm::detail::NamedType<float, adm::HeightTag>; typename adm::detail::ParameterTraits<Parameter>::tag = adm::HeightTag]’
   62 |       ADM_EXPORT bool has(typename detail::ParameterTraits<T>::tag) const {
      |                       ^~~
../include/adm/detail/magic_base.hpp:62:27: note:   no known conversion for argument 1 from ‘Tag’ {aka ‘adm::AudioBlockFormatObjectsTag’} to ‘adm::detail::ParameterTraits<adm::detail::NamedType<float, adm::HeightTag> >::tag’ {aka ‘adm::HeightTag’}
   62 |       ADM_EXPORT bool has(typename detail::ParameterTraits<T>::tag) const {
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It would be nice to move the `OptionalBase` methods to an implementation file; that should be doable.

There's also only one default for each parameter (whereas there could potentially be diferent defaults in different contexts), but it would be pretty easy to add that through another `OptionalBase` parameter.

It's probably not worth doing this just for the audioBlockFormat sub-classes, but if we use this more generally it would eliminate a lot of code, and make it much easier to share parameters between various elements.

**Comment by rsjtaylor** [comment]
While we're having random thoughts, on the subject of better errors:

I thought we might be able to do something with a templated failure case and a static assert to catch the case where you ask for an unsupported parameter. 

Anyway, this was my attempt at hacking in that to the current tag dispatch case, not sure how easy it is to extend to any of these.

```is_same_type_v``` probably isn't the best way of doing it either, was just the first idea I thought of, but general idea of some generic failure case we never actually want to hit but that will static_assert to false.

```c++
#include <iostream>
#include <type_traits>
struct PTag {};

struct BadTag {};

struct BadValue {
    template<typename T>
    // convert to anything so failure case get() always compiles.
    // can omit at the expense of slightly noisier errors, still hits assert
    operator T(){return T{};}; 
};

struct Param {
    using tag = PTag;
};

struct UnsupportedParam {
    UnsupportedParam() = delete;
    using tag = BadTag;
};


struct S {
    public:
    template<typename T>
    T get() {
        // the get should always return the type asked for?
        // probably need to remove qualifiers before the check in practice
        static_assert(std::is_same_v<decltype(get_(typename T::tag())),T>, "bad parameter");
        return get_(typename T::tag());
    };
    private:

    Param get_(PTag tag) {
        std::cout << "Got a P\n";
        return Param{};
    }

    template <typename T>
    BadValue get_(T badTag) {
        return BadValue{};
    }
};

int main() {
   S s;
   s.get<Param>(); // ok
   s.get<UnsupportedParam>(); // nope
}
```

**Comment by tomjnixon** [comment]
The current version now doesn't require all methods to be implemented for all parameters. This allows it to be used for required parameters (like IDs), and it should be easily extendable to implement list parameters (with add and remove).

It's not entirely clear that it's worth it (it was harder than I expected) -- it would be a lot simpler if this was just used for normal optional parameters, or if the different types were combined together in the element types, but I quite like the amount of duplication this could remove.
